"""Add document and chunk tables

Revision ID: 31f0f34ecbbb
Revises: 7cd10a4ac549
Create Date: 2026-07-12 20:46:58.985888

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "31f0f34ecbbb"
down_revision: str | None = "7cd10a4ac549"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document",
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("source_format", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_document_owner_id"), "document", ["owner_id"], unique=False)
    op.create_table(
        "chunk",
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("section_label", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chunk_document_id"), "chunk", ["document_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chunk_document_id"), table_name="chunk")
    op.drop_table("chunk")
    op.drop_index(op.f("ix_document_owner_id"), table_name="document")
    op.drop_table("document")
    # ### end Alembic commands ###
